name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    container: rockylinux:8
    steps:
    - uses: actions/checkout@v2
    - name: prerequisites
      run: |
        dnf -y install make wget git xz
    - name: lint
      run: |
        make lint
  publish_docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REQUIREMENTS: devrequirements.txt
          EXTRA_PACKAGES: build-base libffi-dev rust
