name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: rockylinux:8
    steps:
    - uses: actions/checkout@v2
    - name: prerequisites
      run: |
        dnf -y install make wget git
    - name: lint
      run: |
        make lint
