name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    container: rockylinux:8
    steps:
    - name: prerequisites
      run: |
        dnf -y install make wget git xz findutils git
    - uses: actions/checkout@v2
    - name: devenv
      run: |
        make devenv
    - name: lint
      run: |
        make lint
    - name: publish_docs
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      run: |
        make htmldoc
        remote_repo="https://x-access-token:${GITHUB_TOKEN}@${GITHUB_DOMAIN:-"github.com"}/${GITHUB_REPOSITORY}.git"
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.${GITHUB_DOMAIN:-"github.com"}"
        git remote rm origin
        git remote add origin "${remote_repo}"
        source venv/bin/activate && mkdocs gh-deploy --config-file mkdocs.yml --force
